### PR TITLE
Add remove tabs

### PR DESCRIPTION
**Pull request by stanipintjuk**

### CODE REVIEW

**Comment by Lonami** [comment]
Nice! Let's test it. Do you prefer me to make a pull request with the new strings or you squash those?

`values/strings.xml`:

``` xml
<string name="text_new_tab_name">Write the tab name</string>
<string name="text_add_tab">Add tab</string>
```

`values-es/strings.xml`:

``` xml
<string name="text_new_tab_name">Escribe el nombre de la pestaña</string>
<string name="text_add_tab">Añadir pestaña</string>
```

`values-de/strings.xml`: @Teyro help please!

**Comment by Lonami** [comment]
BTW, since you cannot remove the first tab, shouldn't the user have some feedback instead silently ignoring the action? Either a disabled "Remove" button, not displaying it at all, or another message notifying the user.

**Comment by Lonami** [comment]
Also, after renaming a tab, if you rename it again, it has the old first name instead the updated one. It only "fully updates" after the launcher has been closed and opened again (clearing the cache doesn't work, which by the way was over 10MB already).

**Comment by stanipintjuk** [comment]
@XyLoNaMiyX Yes they should have some kind of feedback that tells them that they cannot remove that tab. I will add that soon. I am also currently adding some more text so please wait before translating, so we can translate everything at the sametime.

**Comment by stanipintjuk** [comment]
@XyLoNaMiyX ooh good catch. but the tab actually does update the name it just the notice "Renaming tab «name»"  that doesn't change.

**Pull request merged**
