### PR TITLE
Added Bulgarian translation

### PR DESCRIPTION
**Pull request by ImAnnoying**

### CODE REVIEW

**Comment by Lonami** [comment]
Thanks! My pull request hasn't yet been merged, but it has another `string`. Could you please provide a translation too?

``` xml
<string name="text_cannot_move_tab">Cannot move this tab</string>
```

**Comment by ImAnnoying** [comment]
I'm new to GitHub, how do I do that? :D Or do I just make a new pull request?

**Comment by Lonami** [comment]
Haha, I was new too. I learnt a lot with this project anyway. Now you should `squash` those 4 commits into one, not to fill the original project history with unnecessary commits.
1. First do `git rebase -i HEAD~4`. This will let you edit the last 4 commits you made.
2. Then, change `pick` for `squash` in those you want to "squash" (those little ones! squash'em'all!)
3. Then it will ask you for a new commit message. Simply leave `"Added Bulgarian translation"`, since that's all you've done.
4. Then you need to push your job to GitHub, with probably `git push --force` since you rebased, so it overrides changes.

But since @stanipintjuk knows more than I, just in case, and if I were you, I would copy the whole folder somewhere else. You know, in case things get screwed up or something.

**Comment by stanipintjuk** [comment]
More translations, awesome! :) 

Everything looks good but as @XyLoNaMiyX said it would be nice if you squashed the commits into one. Here is another [guide](https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/) on how to do it.

Otherwise - well done :)

**Comment by ImAnnoying** [comment]
I think I did it. Thanks!

**Comment by Lonami** [comment]
Haha yep! You did it right :). Awesome.

**Comment by stanipintjuk** [comment]
Thanks! :)

**Pull request merged**
