### PR TITLE
Added a new launcher icon and Spanish translation

### PR DESCRIPTION
**Pull request by Lonami**
I just wanted to see an icon which wasn't the default one so I made this! :P

### CODE REVIEW

**Comment by stanipintjuk** [comment]
This is awesome :D
I will check it out now then merge

Thank you!

**Comment by Lonami** [comment]
Do you like the logo? :D

**Comment by stanipintjuk** [comment]
Ofcourse I did. That is why I merged it :)

**Comment by Lonami** [comment]
Haha maybe you only did for the translation 👀 :)

**Pull request merged**
