### PR TITLE
add french translation

### PR DESCRIPTION
**Pull request by tl-pierre**

### CODE REVIEW

**Comment by stanipintjuk** [comment]
This is really awesome, thank you! But could you wait a little while, because I am adding some more text right now. I think it would be better if everything is translated at the same time at the end.

**Comment by tl-pierre** [comment]
Ok, no problem :)

**Comment by stanipintjuk** [comment]
Good job with the pull request btw :)

**Comment by tl-pierre** [comment]
Haha thank you !

**Comment by stanipintjuk** [comment]
Great! Thank you for updating :)

**Comment by stanipintjuk** [comment]
Hi @Pierre-lbt , I am planning to update the f-droid version so can you provide a translation for these sentences please :)

```
Cannot move this tab
Move
Please tap the tab to be swapped, or the same to cancel
Operation cancelled
```

**Comment by tl-pierre** [comment]
Hi @stanipintjuk and thank you for this new update ! 

```
1)Cannot move this tab = Vous ne pouvez pas déplacer cet onglet
2)Move = Déplacer
3)Please tap the tab to be swapped, or the same to cancel = Appuyez sur l'onglet pour changer sa position, appuyez à nouveau pour annuler l'opération
4)Operation cancelled = opération annulée
```

I'm not sure I understand the third sentence: the user tap one time the tab to change the position of the tab and tap again if he wants to cancel the operation ? If I understood correctly, the translation is correct, otherwise I would like you to explain to me again, I'll try to respond quickly :)

**Comment by Lonami** [comment]
Yes: If the user taps the same tab they wanted to move, then the operation is cancelled (obviously, it can't move to the same tab location, because no movement is made). If, on the other hand, they tap another tab, then both are swapped.

**Comment by tl-pierre** [comment]
Thank you @XyLoNaMiyX, now I understand !
So the final translation is : 

```
1)Cannot move this tab = Vous ne pouvez pas déplacer cet onglet
2)Move = Déplacer
3)Please tap the tab to be swapped, or the same to cancel = Appuyez sur un autre onglet pour échanger la position des deux onglets ou appuyez sur le même onglet pour annuler l'opération.
4)Operation cancelled = Opération annulée
```

**Comment by Lonami** [comment]
Thank you @Pierre-lbt for translating them into French :)

The third translation is really long (for a toast)! Can you think of a better way to put it? I mean, I find it long even in English, but I couldn't think of any better string 😕.

**Comment by tl-pierre** [comment]
Yes I understand, I saw that the German translation is long to :/ An another french translation is possible :

```
3)Please tap the tab to be swapped, or the same to cancel = Appuyez sur un onglet pour échanger les positions, appuyez sur le même onglet pour annuler l'opération
```

I think it is a little less understandable but at least it's shorter. (I couldn't make a translation shorter than that)

**Comment by Lonami** [comment]
Hmm, I think being more understandable is more important. I guess it can't really be rephrased without losing information.

**Comment by tl-pierre** [comment]
I propose to put the "long version" in this update and if the toast is really annoying, you will be able to put the "short version" in the next update. What do you think ?

**Comment by Lonami** [comment]
Yeah, we can always update the string, at any given moment. What I find annoying is that for some reason tapping does not make the toast disappear, it did in older Android versions :(

But that's not related to Silverfish so anyway

**Pull request merged**
