### PR TITLE
Added functionality to rename tabs, cleaned code

### PR DESCRIPTION
**Pull request by Lonami**
To rename a tab, hold the tab you want to rename. An empty name or cancelling cancels the operation.
There is no way to set the default names back again rather than deleting the application data, unless you type it by hand

### CODE REVIEW

**Comment by Lonami** [comment]
It looks like a lot of code, but really I just moved some stuff around (always in the same file, I'm running it on my phone and everything works fine) to put the methods in their corresponding regions. The little important bit is the renaming functionality.

What I did was some changes to keep the code consistency, such as changing:
`}else{`
for
`} else {`
so everywhere looks the same, or adding a space after the comments double slash. It looks more professional! And I think that's it, I wanted to tidy it up a bit :P

**Comment by stanipintjuk** [comment]
This is good, well done! 

But before merging I am wondering if it is a good idea to let the user rename the first tab, since it is a special tab for apps without a category, and all the recently installed apps will always be placed there. So it should technically always be named "Other" or "Uncategorized apps" otherwise it might lead to confusion.
Or what do you think?

**Comment by Lonami** [comment]
I think it doesn't matter, if the user wants to rename it, then he may have a reason :)

Anyway, that would be as easy as add a check for the tabno being 1 :P 

Perhaps he wants to rename it to General, or Unsorted, or New!

**Comment by stanipintjuk** [comment]
I guess that you are right.

Now that you have commited so much maybe it is time to add a "contributors" file or something, just to give you and other contributors some cred.

**Pull request merged**
