### PR TITLE
Implemented swiping down to open notifications panel and more fixes

### LINKED ISSUE #31: Please add support for swiping down on the background to open the notification panel
As the title states. Whenever I pull down on empty space (I.e. I'm not scrolling the widget or app list) I'd like to have the notification panel expand. Easy access to the notifications without having to stretch my thumb all the way to the top of my device.

### PR DESCRIPTION
**Pull request by Lonami**
Fixes #31

### CODE REVIEW

**Comment by stanipintjuk** [comment]
Nice! But it doesn't work when dragging over views that use a click listener like the shortcut buttons. I suggest that you extend the `View` class and override the `onInterceptTouchEvent` so that it returns `true` when the speed threshold is exceeded. Here is some relevant documentation https://developer.android.com/training/gestures/viewgroup.html

**Comment by Lonami** [comment]
Don't merge yet. Fixing a bug usually introduces another: now we're not able to remove the icons from the home screen. Should be easy enough to fix.

**Comment by Lonami** [comment]
OK fixed. I amended (I only had to change one line). Changes should be reflected here!

**Comment by stanipintjuk** [comment]
Love it! Thank you! 😸

**Pull request merged**
